### ISSUE TITLE
Refresh Trouble

### ISSUE THREAD

**Issue by 0xbadb0d00** [vitoplantamura/BugChecker#10]
Hello Vito,
For first I want to congratulate with you for this wonderful tool (nostalgia time :) ).

I tried it on VirtualBox, but I noticed that if I don't change the focus at the VirtualBox screen, it can't refresh the screen when I write the commands in the console. How can I solve it?

Another question: have you implemented the "poi" (pointer) command?

Is it possibile to write a Javascript like this, to write a Unicode string: ? dq(poi(r8 + 10) + 0x8).toString()

Ciao e grazie!

**Comment by vitoplantamura** [comment]
Grazie!!

I didn't quite understand the problem with VirtualBox :-)

Regarding the "poi" command instead, to be able to dereference a pointer
and print the memory in BugChecker, I would try this command (which should
be the equivalent of yours):

db await ReadMem( r8 + 10, 1, 8 )[0] + 0x8

The third argument of ReadMem is the pointer size (4 for 32bit and 8 for
64bit).

Vito

**Comment by 0xbadb0d00** [comment]
> Grazie!! I didn't quite understand the problem with VirtualBox :-) Regarding the "poi" command instead, to be able to dereference a pointer and print the memory in BugChecker, I would try this command (which should be the equivalent of yours): db await ReadMem( r8 + 10, 1, 8 )[0] + 0x8 The third argument of ReadMem is the pointer size (4 for 32bit and 8 for 64bit). Vito

Ciao Vito,
regarding the VirtualBox problem I mean this: when I have the BugChecker window active on the screen of the VirtualBox guest operating system, and I try to write something with the keyboard, what I write is not seen immediately, but only after I have lost the focus of the VirtualBox window and be returned to its screen again. It's as if the BugChecker window refresh isn't immediate, among other things I don't even see the cursor blink while I use BugChecker.

Thanks so much for the dereferencing tip.

**Comment by vitoplantamura** [comment]
ok now it's clear :-)

So in the VM's Display Settings try setting "Graphics Controller" to "VBoxSVGA" and deactivating "3D Acceleration".

Let me know if it works!

Ciao, Vito

**Comment by 0xbadb0d00** [comment]
> ok now it's clear :-)
> 
> So in the VM's Display Settings try setting "Graphics Controller" to "VBoxSVGA" and deactivating "3D Acceleration".
> 
> Let me know if it works!
> 
> Ciao, Vito

Thanks for your response and interest. Unfortunately I already had these settings

**Comment by vitoplantamura** [comment]
I didn't ask you something important: did you disable the display drivers
in Windows before opening BugChecker?

**Comment by 0xbadb0d00** [comment]
> I didn't ask you something important: did you disable the display drivers in Windows before opening BugChecker?

Thank you Vito!!!! It worked!!!!!! 

Only one problem remains: when I try to dereference the structure pointer of the call to **NtOpenFile** to read the **ObjectName** of the **ObjectAttributes** parameter:
<img width="488" alt="VirtualBoxVM_TTVx0CAn6e" src="https://github.com/vitoplantamura/BugChecker/assets/58396344/0fc580aa-9a82-41fa-9581-2360c25de3ac">
I get this error. The address inside Object array it's ok, but if I try to access it by doing **"[0]"** it returns and error.

**Comment by vitoplantamura** [comment]
oops, I think the await operator has lower precedence than the [] operator.
So something like this should work:

db (await ReadMem( r8 + 10, 1, 8 ))[0] + 0x8

Vito

**Comment by 0xbadb0d00** [comment]
> oops, I think the await operator has lower precedence than the [] operator. So something like this should work: db (await ReadMem( r8 + 10, 1, 8 ))[0] + 0x8 Vito

It works, thank you very much, Vito.

To print the Unicode string, I wrote:

db (await ReadMem((await ReadMem(r8+0x10, 1, 0x8))[0]+0x8, 1, 0x8))[0]
